### ISSUE TITLE
New Zealand Flag

### ISSUE THREAD

**Issue by Countryman98** [dedevillela/VRS-Country-Flags#2]
What the chance of having a New Zealand flag added to the package please?
Thanks

**Comment by dedevillela** [comment]
Hi Coutryman98,

Thanks on your interest in the plugin. I've just added the kiwi flag, as requested.

https://github.com/dedevillela/VRS-Country-Flags/commit/c876e3a76a81579f46fbe337188c044314cab543

Best regards,

**Comment by Countryman98** [comment]
Thanks for your time!
